; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\23001\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
